/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalCulator;

/**
 *
 * @author LENOVO
 */
public class calcutor1 extends javax.swing.JFrame {

    double f_num,s_num,result;
    String operation,answer;
    public calcutor1() {
        initComponents();
        this.setBounds(100,50,400,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        btnclean = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnplush = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnminas = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnintu = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnans = new javax.swing.JButton();
        btndevide = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(60, 10, 270, 40);

        btnclean.setText("C");
        btnclean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncleanActionPerformed(evt);
            }
        });
        getContentPane().add(btnclean);
        btnclean.setBounds(270, 80, 60, 40);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(60, 200, 60, 40);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(130, 200, 60, 40);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(200, 200, 60, 40);

        btnplush.setText("+");
        btnplush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplushActionPerformed(evt);
            }
        });
        getContentPane().add(btnplush);
        btnplush.setBounds(270, 140, 60, 40);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(60, 140, 60, 40);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(130, 140, 60, 40);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(200, 140, 60, 40);

        jButton9.setText("1");
        getContentPane().add(jButton9);
        jButton9.setBounds(270, 140, 50, 25);

        jButton10.setText("1");
        getContentPane().add(jButton10);
        jButton10.setBounds(200, 140, 50, 25);

        jButton11.setText("1");
        getContentPane().add(jButton11);
        jButton11.setBounds(60, 140, 50, 25);

        jButton12.setText("1");
        getContentPane().add(jButton12);
        jButton12.setBounds(130, 140, 50, 25);

        btnminas.setText("-");
        btnminas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminasActionPerformed(evt);
            }
        });
        getContentPane().add(btnminas);
        btnminas.setBounds(270, 200, 60, 40);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(60, 80, 60, 40);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(130, 80, 60, 40);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(200, 80, 60, 40);

        jButton17.setText("1");
        getContentPane().add(jButton17);
        jButton17.setBounds(270, 200, 50, 25);

        btnintu.setText("*");
        btnintu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnintuActionPerformed(evt);
            }
        });
        getContentPane().add(btnintu);
        btnintu.setBounds(270, 260, 60, 40);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0);
        btn0.setBounds(60, 260, 60, 40);

        btnans.setText("=");
        btnans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnansActionPerformed(evt);
            }
        });
        getContentPane().add(btnans);
        btnans.setBounds(130, 260, 60, 40);

        btndevide.setText("/");
        btndevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndevideActionPerformed(evt);
            }
        });
        getContentPane().add(btndevide);
        btndevide.setBounds(200, 260, 60, 40);

        jButton25.setText("1");
        getContentPane().add(jButton25);
        jButton25.setBounds(270, 260, 50, 25);

        jButton26.setText("1");
        getContentPane().add(jButton26);
        jButton26.setBounds(200, 260, 50, 25);

        jButton27.setText("1");
        getContentPane().add(jButton27);
        jButton27.setBounds(60, 260, 50, 25);

        jButton28.setText("1");
        getContentPane().add(jButton28);
        jButton28.setBounds(130, 260, 50, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String get = display.getText();
        display.setText(get+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String get = display.getText();
        display.setText(get+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String get = display.getText();
        display.setText(get+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String get = display.getText();
        display.setText(get+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String get = display.getText();
        display.setText(get+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String get = display.getText();
        display.setText(get+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String get = display.getText();
        display.setText(get+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String get = display.getText();
        display.setText(get+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String get = display.getText();
        display.setText(get+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String get = display.getText();
        display.setText(get+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnplushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplushActionPerformed
        f_num = Double.parseDouble(display.getText());
        display.setText("");
        operation = "+";
    }//GEN-LAST:event_btnplushActionPerformed

    private void btnminasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminasActionPerformed
       f_num = Double.parseDouble(display.getText());
        display.setText("");
        operation = "-";
    }//GEN-LAST:event_btnminasActionPerformed

    private void btnintuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnintuActionPerformed
       f_num = Double.parseDouble(display.getText());
        display.setText("");
        operation = "*";
    }//GEN-LAST:event_btnintuActionPerformed

    private void btndevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndevideActionPerformed
        f_num = Double.parseDouble(display.getText());
        display.setText("");
        operation = "/";
    }//GEN-LAST:event_btndevideActionPerformed

    private void btnansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnansActionPerformed
        s_num = Double.parseDouble(display.getText());
        switch(operation)
        {
            case "+":
                result = f_num + s_num ;
                answer = String.format("%.0f",result);
                display.setText(answer);
                break;
                
            case "-":
                result = f_num - s_num ;
                answer = String.format("%.0f",result);
                display.setText(answer);
                break;
            
            case "*":
                result = f_num * s_num ;
                answer = String.format("%.0f",result);
                display.setText(answer);
                break;    
            
            case "/":
                result = f_num / s_num ;
                answer = String.format("%.0f",result);
                display.setText(answer);
                break;    
        }
    }//GEN-LAST:event_btnansActionPerformed

    private void btncleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncleanActionPerformed
       display.setText("");
    }//GEN-LAST:event_btncleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcutor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcutor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcutor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcutor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcutor1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnans;
    private javax.swing.JButton btnclean;
    private javax.swing.JButton btndevide;
    private javax.swing.JButton btnintu;
    private javax.swing.JButton btnminas;
    private javax.swing.JButton btnplush;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
